title = "Rain Test"
working_dir = "/home/awolf/dev/rain-test/example-project/.working/"
tests = [
    "/home/awolf/dev/rain-test/example-project/tests/test_sensor.c",
    "/home/awolf/dev/rain-test/example-project/tests/test_sensor2.c",

]
sources = [
    "/home/awolf/dev/rain-test/c/rain.c",
]
includes = [
    "/home/awolf/dev/rain-test/c/",
]


